// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAYMvWe1BHcdPBy_g2mnwU90qzPUYCnF6E',
    appId: '1:213795493196:android:fa442c141017e4cd1cebe9',
    messagingSenderId: '213795493196',
    projectId: 'madwell-staging-eb57e',
    storageBucket: 'madwell-staging-eb57e.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB8O0S2F4WN2u8W6-bOqjLp2AOO1R4jioY',
    appId: '1:213795493196:ios:daf0f13fc57745be1cebe9',
    messagingSenderId: '213795493196',
    projectId: 'madwell-staging-eb57e',
    storageBucket: 'madwell-staging-eb57e.firebasestorage.app',
    androidClientId: '213795493196-fhu566kcqk7va0g49nii0tk6r6t8nhgb.apps.googleusercontent.com',
    iosClientId: '213795493196-lj8sovmuplh4sp7td5ul5dri7kaqbu1e.apps.googleusercontent.com',
    iosBundleId: 'app.madwell.pro.customer',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB8CndmCmuok4MdCXj3Q_8X4I9im5RFiUQ',
    appId: '1:213795493196:web:ee02ebe966719ec61cebe9',
    messagingSenderId: '213795493196',
    projectId: 'madwell-staging-eb57e',
    authDomain: 'madwell-staging-eb57e.firebaseapp.com',
    storageBucket: 'madwell-staging-eb57e.firebasestorage.app',
    measurementId: 'G-6SCLY8Z5M1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB8O0S2F4WN2u8W6-bOqjLp2AOO1R4jioY',
    appId: '1:213795493196:ios:a35a198f3365accf1cebe9',
    messagingSenderId: '213795493196',
    projectId: 'madwell-staging-eb57e',
    storageBucket: 'madwell-staging-eb57e.firebasestorage.app',
    iosClientId: '213795493196-d3c2buekql5a26q536gk0vs8scj8i610.apps.googleusercontent.com',
    iosBundleId: 'app.madwell.pro',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB8CndmCmuok4MdCXj3Q_8X4I9im5RFiUQ',
    appId: '1:213795493196:web:e5275695ee9af8611cebe9',
    messagingSenderId: '213795493196',
    projectId: 'madwell-staging-eb57e',
    authDomain: 'madwell-staging-eb57e.firebaseapp.com',
    storageBucket: 'madwell-staging-eb57e.firebasestorage.app',
    measurementId: 'G-W16T5JBZ6M',
  );

}