// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options_staging.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAYMvWe1BHcdPBy_g2mnwU90qzPUYCnF6E',
    appId: '1:213795493196:android:0f9a9950717fbe9f1cebe9',
    messagingSenderId: '213795493196',
    projectId: 'madwell-staging-eb57e',
    storageBucket: 'madwell-staging-eb57e.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB8O0S2F4WN2u8W6-bOqjLp2AOO1R4jioY',
    appId: '1:213795493196:ios:1c41e4acf7a8567a1cebe9',
    messagingSenderId: '213795493196',
    projectId: 'madwell-staging-eb57e',
    storageBucket: 'madwell-staging-eb57e.firebasestorage.app',
    androidClientId: '213795493196-fhu566kcqk7va0g49nii0tk6r6t8nhgb.apps.googleusercontent.com',
    iosClientId: '213795493196-8o5t5g8sle5bo74g0mgh22r0b2m2dk14.apps.googleusercontent.com',
    iosBundleId: 'app.madwell.pro.customer.staging',
  );
}
