name: Build & Deploy Flutter App

on:
  push:
    branches:
      - main
    tags:
      - 'v*' # runs on tags like v1.0.0

jobs:
  build-android:
    name: Build Android AAB
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source
        uses: actions/checkout@v3

      - name: Remove any cached Flutter
        run: rm -rf "$HOME/.flutter"

      - name: Setup Flutter v3.29.3 (Dart ≥ 3.6.0)
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.29.3'
          cache: false

      - name: Confirm Flutter & Dart versions
        run: flutter --version

      - name: Install Dart dependencies
        run: flutter pub get

      - name: Build Android AAB
        run: flutter build appbundle --release

      - name: Upload Android AAB Artifact
        uses: actions/upload-artifact@v3
        with:
          name: android-appbundle
          path: build/app/outputs/bundle/release/app-release.aab

  build-ios:
    name: Build iOS App
    runs-on: macos-latest
    steps:
      - name: Checkout source
        uses: actions/checkout@v3

      - name: Remove any cached Flutter
        run: rm -rf "$HOME/.flutter"

      - name: Setup Flutter v3.29.3 (Dart ≥ 3.6.0)
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.29.3'
          cache: false

      - name: Confirm Flutter & Dart versions
        run: flutter --version

      - name: Install Dart dependencies
        run: flutter pub get

      - name: Build iOS app (no codesign)
        run: flutter build ios --release --no-codesign

      - name: Upload iOS App Artifact
        uses: actions/upload-artifact@v3
        with:
          name: ios-app
          path: build/ios/iphoneos/Runner.app

  download-artifacts:
    name: Download Build Artifacts
    runs-on: ubuntu-latest
    needs: [build-android, build-ios]
    steps:
      - name: Download Android Artifact
        uses: actions/download-artifact@v3
        with:
          name: android-appbundle
          path: artifacts/android

      - name: Download iOS Artifact
        uses: actions/download-artifact@v3
        with:
          name: ios-app
          path: artifacts/ios

      - name: List downloaded files
        run: |
          echo "Android artifacts:" && ls -R artifacts/android
          echo "iOS artifacts:" && ls -R artifacts/ios

  publish-android:
    name: Publish Android App
    runs-on: ubuntu-latest
    needs: download-artifacts
    steps:
      - name: Checkout source
        uses: actions/checkout@v3

      - name: Setup Ruby for Fastlane
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.1'

      - name: Install Fastlane gems
        run: |
          cd android
          bundle install

      - name: Deploy to Google Play (fastlane beta)
        env:
          SUPPLY_JSON_KEY: ${{ secrets.GOOGLE_PLAY_JSON_KEY }}
        run: |
          cd android
          echo "$SUPPLY_JSON_KEY" > service_account.json
          fastlane beta

  publish-ios:
    name: Publish iOS App
    runs-on: macos-latest
    needs: download-artifacts
    steps:
      - name: Checkout source
        uses: actions/checkout@v3

      - name: Setup Ruby for Fastlane
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.1'

      - name: Install Fastlane gems
        run: |
          cd ios
          bundle install

      - name: Decode Apple certificates & profiles
        env:
          IOS_CERTIFICATE_BASE64: ${{ secrets.IOS_CERTIFICATE_BASE64 }}
          IOS_PROVISION_PROFILE_BASE64: ${{ secrets.IOS_PROVISION_PROFILE_BASE64 }}
          IOS_KEYCHAIN_PASSWORD: ${{ secrets.IOS_KEYCHAIN_PASSWORD }}
        run: |
          mkdir -p ~/certs
          echo "$IOS_CERTIFICATE_BASE64" | base64 --decode > ~/certs/cert.p12
          echo "$IOS_PROVISION_PROFILE_BASE64" | base64 --decode > ~/certs/profile.mobileprovision

      - name: Deploy to App Store (fastlane release)
        env:
          MATCH_PASSWORD: ${{ secrets.MATCH_PASSWORD }}
          APP_STORE_CONNECT_API_KEY: ${{ secrets.APP_STORE_CONNECT_API_KEY }}
        run: |
          cd ios
          fastlane release
